"// Configuration options"
"{"
"    // Default encoding for text"
"   \"encoding\" : \"UTF-8\","
"    \"number\": 3.34E-5,"
"    // Plug-ins loaded at start-up"
"    \"plug-ins\" : ["
"        \"python\","
"        \"c++\","
"        \"ruby\""
"	 ],"
"        "
"	// Tab indent size"
"    \"indent\" : { \"length\" : 3, "use_space": true },"
"    "
"    // set of languages"
"    \"languages\":[{"
"    "
"	    \"code\" : \"en\","
"	    \"text\": \"Hello world!\""
"	},{"
"	    "
"	    \"code\" : \"es\","
"	    \"text\": \"Hola mundo!\""
	"}]"
"}"
